# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IlnKCqXeeNuQP7jfI3yFr-A2rkCfpmAe
"""

def string_alternative(st):
    result = st[::2]
    print(result)
 
fname = input(" enter first name : ")
lname = input(" enter last name : ")
st = fname +" "+lname

print( st)
string_alternative(st)

l1=[]
n=int(input())
for i in range(n):
  l1.append(int(input()))
op=[i/2.54 for i in l1]
print(op)

f=open("./sample_data/input.txt","r")
d=dict()
for x in f:
  for i in x.strip("\n").split(" "):
    if i in d.keys():
       d[i]+=1
    else:
      d[i]=1
f.close()
print("Word count")
f1=open("./sample_data/output.txt","w")
for i in d.keys():
   f1.write(i+":"+(d[i].__str__())+"\n")
   print(i+":"+(d[i].__str__()))
f1.close()